[package]
name = "reposync"
version = "0.1.0"
edition = "2024"

[dependencies]
octocrab = { version = "0.44.1", features = ["stream"] }
reqwest = { version = "0.12", features = ["json","blocking"] }
tokio = { version = "1", features = ["full"] }
serde_json = "1.0"
serde = "1.0.219"
