name: build linux release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

# apt update && apt install git curl build-essential gcc-x86-64-linux-gnu -y
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# source ~/.cargo/env
# rustup target add x86_64-unknown-linux-gnu
# export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/x86_64-linux-gnu-gcc
# cargo build --target=x86_64-unknown-linux-gnu


jobs:
  build-linux-arm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install aarch64 cross-compilation tools
        run: sudo apt-get install -y gcc-aarch64-linux-gnu build-essential

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          target: aarch64-unknown-linux-gnu
          toolchain: stable

      - name: set linker
        run: echo "export CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/aarch64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build Rust binary
        run: cargo build --release --target aarch64-unknown-linux-gnu

      - name: Rename binary
        run: mv target/aarch64-unknown-linux-gnu/release/reposync target/aarch64-unknown-linux-gnu/release/reposync-aarch64-unknown-linux-gnu

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/aarch64-unknown-linux-gnu/release/reposync-aarch64-unknown-linux-gnu
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

build-linux-x86:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install x86_64 cross-compilation tools
        run: sudo apt-get install -y gcc-x86-64-linux-gnu build-essential

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          target: x86_64-unknown-linux-gnu
          toolchain: stable

      - name: set linker
        run: echo "export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/x86_64-linux-gnu-gcc" >> $GITHUB_ENV

      - name: Build Rust binary
        run: cargo build --release --target x86_64-unknown-linux-gnu

      - name: Rename binary
        run: mv target/x86_64-unknown-linux-gnu/release/reposync target/x86_64-unknown-linux-gnu/release/reposync-x86_64-unknown-linux-gnu

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-gnu/release/reposync-x86_64-unknown-linux-gnu
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
