name: build linux release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture: [x86_64-unknown-linux-gnu,
        #  aarch64-unknown-linux-gnu
         ]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install aarch64 cross-compilation tools
        run: sudo apt-get install -y gcc-aarch64-linux-gnu

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          profile: minimal
          target: ${{ matrix.architecture }}
          toolchain: stable

      - name: Install cross
        run: cargo install cross --git https://github.com/cross-rs/cross
      
      - name: Build Rust binary
        run: cross cargo build --release --target ${{ matrix.architecture }}

      - name: Rename binary
        run: mv target/${{ matrix.architecture }}/release/reposync target/${{ matrix.architecture }}/release/reposync-${{ matrix.architecture }}

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.architecture }}/release/reposync-${{ matrix.architecture }}
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
