name: build releases

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

# apt update && apt install git curl build-essential gcc-x86-64-linux-gnu -y
# curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
# source ~/.cargo/env
# rustup target add x86_64-unknown-linux-gnu
# export CARGO_TARGET_X86_64_UNKNOWN_LINUX_GNU_LINKER=/usr/bin/x86_64-linux-gnu-gcc
# cargo build --target=x86_64-unknown-linux-gnu

jobs:
  build-linux:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: x86_64-unknown-linux-gnu
          - os: ubuntu-24.04-arm
            arch: aarch64-unknown-linux-gnu
          - os: macos-latest
            arch: x86_64-apple-darwin
          - os: macos-latest
            arch: aarch64-apple-darwin
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          target: aarch64-unknown-linux-gnu
          toolchain: stable

      - name: Build Rust binary
        run: cargo build --release --target ${{ matrix.arch }}

      - name: Rename binary
        run: mv target/${{ matrix.arch }}/release/reposync target/${{ matrix.arch }}/release/reposync-${{ matrix.arch }}

      - name: Upload binary
        uses: softprops/action-gh-release@v2
        with:
          files: target/${{ matrix.arch }}/release/reposync-${{ matrix.arch }}
          tag_name: v1.0.${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
